export const goods = [
  {
    id: '1',
    name: 'Товар 1',
    email: 'test@mail.ru',
    price: 1034500,
    count: 5,
    delivery: 'no',
    country: '',
    city: '',
  },
  {
    id: '3',
    name: 'Товар 3',
    email: 'test3@mail.ru',
    price: 1567000,
    count: 10,
    delivery: 'yes',
    country: 'США',
    city: ['Вашингтон', 'Лос-Анджелес'],
  },
  {
    id: '2',
    name: 'Товар 2',
    email: 'test2@mail.ru',
    price: 1234000,
    count: 4,
    delivery: 'yes',
    country: 'Россия',
    city: ['Москва'],
  },
];
